# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import assetproto.designation_pb2 as designation__pb2


class DesignationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDesignation = channel.unary_unary(
                '/designations.DesignationService/CreateDesignation',
                request_serializer=designation__pb2.CreateDesignationRequest.SerializeToString,
                response_deserializer=designation__pb2.CreateDesignationRequest.FromString,
                )
        self.GetDesignation = channel.unary_unary(
                '/designations.DesignationService/GetDesignation',
                request_serializer=designation__pb2.GetDesignationRequest.SerializeToString,
                response_deserializer=designation__pb2.CreateDesignationRequest.FromString,
                )


class DesignationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateDesignation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDesignation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DesignationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDesignation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDesignation,
                    request_deserializer=designation__pb2.CreateDesignationRequest.FromString,
                    response_serializer=designation__pb2.CreateDesignationRequest.SerializeToString,
            ),
            'GetDesignation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDesignation,
                    request_deserializer=designation__pb2.GetDesignationRequest.FromString,
                    response_serializer=designation__pb2.CreateDesignationRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'designations.DesignationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DesignationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateDesignation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/designations.DesignationService/CreateDesignation',
            designation__pb2.CreateDesignationRequest.SerializeToString,
            designation__pb2.CreateDesignationRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDesignation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/designations.DesignationService/GetDesignation',
            designation__pb2.GetDesignationRequest.SerializeToString,
            designation__pb2.CreateDesignationRequest.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
