# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: designation.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64\x65signation.proto\x12\x0c\x64\x65signations\">\n\x18\x43reateDesignationRequest\x12\r\n\x05\x64\x65sid\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65signation\x18\x02 \x01(\t\"&\n\x15GetDesignationRequest\x12\r\n\x05\x64\x65sid\x18\x01 \x01(\x05\x32\xdc\x01\n\x12\x44\x65signationService\x12\x65\n\x11\x43reateDesignation\x12&.designations.CreateDesignationRequest\x1a&.designations.CreateDesignationRequest\"\x00\x12_\n\x0eGetDesignation\x12#.designations.GetDesignationRequest\x1a&.designations.CreateDesignationRequest\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'designation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATEDESIGNATIONREQUEST']._serialized_start=35
  _globals['_CREATEDESIGNATIONREQUEST']._serialized_end=97
  _globals['_GETDESIGNATIONREQUEST']._serialized_start=99
  _globals['_GETDESIGNATIONREQUEST']._serialized_end=137
  _globals['_DESIGNATIONSERVICE']._serialized_start=140
  _globals['_DESIGNATIONSERVICE']._serialized_end=360
# @@protoc_insertion_point(module_scope)
