# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: employee.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65mployee.proto\x12\temployees\"r\n\x1b\x43reateUpdateEmployeeRequest\x12\r\n\x05\x65mpid\x18\x01 \x01(\x05\x12\x10\n\x08\x66ullname\x18\x02 \x01(\t\x12\x0e\n\x06salary\x18\x03 \x01(\x02\x12\x13\n\x0b\x64\x65signation\x18\x04 \x01(\t\x12\r\n\x05\x64\x65sid\x18\x05 \x01(\x05\")\n\x18GetDeleteEmployeeRequest\x12\r\n\x05\x65mpid\x18\x01 \x01(\x05\")\n\x16\x44\x65leteEmployeeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\'\n\x14SelectColumnsRequest\x12\x0f\n\x07\x63olumns\x18\x01 \x03(\t\"V\n\x19SelectAllEmployeeResponse\x12\x39\n\temployees\x18\x01 \x03(\x0b\x32&.employees.CreateUpdateEmployeeRequest\"6\n\x1aSelectSalaryByRangeRequest\x12\x0b\n\x03min\x18\x01 \x01(\x02\x12\x0b\n\x03max\x18\x02 \x01(\x02\"\x1e\n\x0fGetRedisRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\" \n\x10GetRedisResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"!\n\x0eGetFormRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\x1f\n\x0c\x46ormResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x32\xf0\x05\n\x0f\x45mployeeService\x12\x62\n\x0e\x43reateEmployee\x12&.employees.CreateUpdateEmployeeRequest\x1a&.employees.CreateUpdateEmployeeRequest\"\x00\x12\\\n\x0bGetEmployee\x12#.employees.GetDeleteEmployeeRequest\x1a&.employees.CreateUpdateEmployeeRequest\"\x00\x12Z\n\x0e\x44\x65leteEmployee\x12#.employees.GetDeleteEmployeeRequest\x1a!.employees.DeleteEmployeeResponse\"\x00\x12\x62\n\x0eUpdateEmployee\x12&.employees.CreateUpdateEmployeeRequest\x1a&.employees.CreateUpdateEmployeeRequest\"\x00\x12\\\n\x11SelectAllEmployee\x12\x1f.employees.SelectColumnsRequest\x1a$.employees.SelectAllEmployeeResponse\"\x00\x12\x64\n\x13SelectSalaryByRange\x12%.employees.SelectSalaryByRangeRequest\x1a$.employees.SelectAllEmployeeResponse\"\x00\x12I\n\x0cGetRedisData\x12\x1a.employees.GetRedisRequest\x1a\x1b.employees.GetRedisResponse\"\x00\x12L\n\x07GetForm\x12\x19.employees.GetFormRequest\x1a$.employees.SelectAllEmployeeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'employee_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATEUPDATEEMPLOYEEREQUEST']._serialized_start=29
  _globals['_CREATEUPDATEEMPLOYEEREQUEST']._serialized_end=143
  _globals['_GETDELETEEMPLOYEEREQUEST']._serialized_start=145
  _globals['_GETDELETEEMPLOYEEREQUEST']._serialized_end=186
  _globals['_DELETEEMPLOYEERESPONSE']._serialized_start=188
  _globals['_DELETEEMPLOYEERESPONSE']._serialized_end=229
  _globals['_SELECTCOLUMNSREQUEST']._serialized_start=231
  _globals['_SELECTCOLUMNSREQUEST']._serialized_end=270
  _globals['_SELECTALLEMPLOYEERESPONSE']._serialized_start=272
  _globals['_SELECTALLEMPLOYEERESPONSE']._serialized_end=358
  _globals['_SELECTSALARYBYRANGEREQUEST']._serialized_start=360
  _globals['_SELECTSALARYBYRANGEREQUEST']._serialized_end=414
  _globals['_GETREDISREQUEST']._serialized_start=416
  _globals['_GETREDISREQUEST']._serialized_end=446
  _globals['_GETREDISRESPONSE']._serialized_start=448
  _globals['_GETREDISRESPONSE']._serialized_end=480
  _globals['_GETFORMREQUEST']._serialized_start=482
  _globals['_GETFORMREQUEST']._serialized_end=515
  _globals['_FORMRESPONSE']._serialized_start=517
  _globals['_FORMRESPONSE']._serialized_end=548
  _globals['_EMPLOYEESERVICE']._serialized_start=551
  _globals['_EMPLOYEESERVICE']._serialized_end=1303
# @@protoc_insertion_point(module_scope)
